### ISSUE TITLE
Bus stop info broken

### ISSUE THREAD

**Issue by andrewgoz** [Sutto/transperth-api#4]
Bus top service queries, like:

http://api.perthtransit.com/1/bus_stops/12331

are not returning any time info. I guess the Transperth site has changed?

**Comment by Sutto** [comment]
Just tried now and it appears to be working? May have just been site downtime?

**Comment by andrewgoz** [comment]
Yes, it's working now. The train times were working at the time, so I assumed the buses should have been too.
